Category.create!([
  {name: "New Fruits Arrive"},
  {name: "Continental Fruits"}
])
Ckeditor::Asset.create!([
  {data_file_name: "ong-2.jpg", data_content_type: "image/jpeg", data_file_size: 76826, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 648, height: 495},
  {data_file_name: "ong-2.jpg", data_content_type: "image/jpeg", data_file_size: 76826, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 648, height: 495},
  {data_file_name: "che-2.jpg", data_content_type: "image/jpeg", data_file_size: 49217, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 623, height: 417},
  {data_file_name: "cho-2.jpg", data_content_type: "image/jpeg", data_file_size: 84957, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 619, height: 465}
])
Contact.create!([
  {name: "Ron Dam", address: "123 Hai Ba Trung", message: "Citrus maxima was originally called \"shaddick\" in English, after the captain of an East India Company ship who introduced it to Jamaica in 1696.[2] The word \"pomelo\" has become the more common name, although \"pomelo\" has historically been used for grapefruit. (The 1973 printing of the American Heritage Dictionary, for example, gives grapefruit as the only meaning of \"pomelo\".)"},
  {name: "Nguyen Van A", address: "321 Ly Chinh Thang", message: "The etymology of the word \"pomelo\" is complex. In the Tamil language it is called \"pampa limāsu\", which means big citrus. The name was adopted by the Portuguese as \"pomposos limões\" and then by the Dutch as \"pompelmoes\". The name can be found with some deviations in many European languages, for example German (Pampelmuse), Latvian (Pampelmūze), Ido (Pompelmuso), whereas some other languages use \"pomelo\" (Turkish, Norwegian, Polish)."},
  {name: "Le Thi B", address: "100 CMT8", message: "Citrus maxima is native to Southeast Asia[4] where it is known under a wide variety of names. In large parts of South East Asia, it is a popular dessert, often eaten raw sprinkled with, or dipped in, a salt mixture. It is also eaten in salads and drinks. It is called in Maithili- टाभ नेबो(taabh nebo) that makes special अर्घ(argh-an offering plate with distinct farm fruit ,tubers and roots) in छठ पूजा (Chhathh Pooja - a two days fast observed and end with worshipping the setting Sun and rising Sun God)."}
])
Product.create!([
  {name: " Pomelo", price: 100000, origin: "Malaysia", description: "Citrus maxima (or Citrus grandis), (Common names: pomelo, pomello, pummelo, pommelo, pamplemousse, jabong (Hawaii), shaddick,[1] or shaddock) is a natural (non-hybrid) citrus fruit, with the appearance of a big grapefruit, native to South and Southeast Asia.", quantity: 100, category_id: 2, price_discount: 90000, status: nil},
  {name: "Pomegranate", price: 95000, origin: "Spain", description: "The pomegranate (/ˈpɒmᵻɡrænᵻt/), botanical name Punica granatum, is a fruit-bearing deciduous shrub or small tree in the family Lythraceae that grows between 5 and 8 m (16 and 26 ft) tall.", quantity: 100, category_id: 2, price_discount: 86000, status: nil},
  {name: "Beetroot", price: 100000, origin: "Malaysia", description: "No information", quantity: 95, category_id: 1, price_discount: 90000, status: nil},
  {name: "Agar Agar", price: 111111, origin: "Singapore", description: "No information", quantity: 97, category_id: 2, price_discount: 100000, status: nil},
  {name: "Persimmon", price: 110000, origin: "Spain", description: "The persimmon /pərˈsɪmən/ (sometimes spelled persimon) is the edible fruit of a number of species of trees in the genus Diospyros", quantity: 99, category_id: 2, price_discount: 100000, status: nil},
  {name: "Jambu", price: 120000, origin: "Thailand", description: "Syzygium cumini, known as jambul, jambolan, jamblang or jamun, is an evergreen tropical tree in the flowering plant family Myrtaceae", quantity: 95, category_id: 2, price_discount: 110000, status: nil},
  {name: "Honeydew", price: 111111, origin: "Singapore", description: "A honeydew melon, also known as a honeymelon, is the fruit of one cultivar group of the muskmelon, Cucumis melo in the gourd family", quantity: 105, category_id: 2, price_discount: 99999, status: nil},
  {name: "Atap Seed", price: 122222, origin: "Vietnam", description: "No information", quantity: 96, category_id: 1, price_discount: 110000, status: nil},
  {name: "Coconut", price: 70000, origin: "Vietnam", description: "No information", quantity: 97, category_id: 1, price_discount: 60000, status: nil},
  {name: "Kiwi", price: 100000, origin: "USA", description: "No information", quantity: 97, category_id: 1, price_discount: 97000, status: nil},
  {name: "Apple", price: 55000, origin: "China", description: "No information", quantity: 34, category_id: 1, price_discount: 50000, status: nil},
  {name: "Avocado", price: 99000, origin: "Indonesia", description: "No information", quantity: 96, category_id: 1, price_discount: 90000, status: nil},
  {name: "Chiku", price: 88000, origin: "Thailand", description: "No information", quantity: 96, category_id: 1, price_discount: 85000, status: nil},
  {name: "Banana", price: 80000, origin: "Vietnam", description: "No information", quantity: 60, category_id: 1, price_discount: 75000, status: nil},
  {name: "Pear", price: 77000, origin: "Hong Kong", description: "No information", quantity: 94, category_id: 1, price_discount: 70000, status: nil},
  {name: "Lychee", price: 100000, origin: "Australia", description: "The lychee, litchi, liechee, liche, lizhi or li zhi, or lichee (Litchi chinensis; Chinese: 荔枝) is the sole member of the genus Litchi in the soapberry family, Sapindaceae", quantity: 100, category_id: 2, price_discount: 90000, status: nil}
])
WishList.create!([
  {user_id: 3, product_id: 4},
  {user_id: 3, product_id: 6},
  {user_id: 3, product_id: 5},
  {user_id: 3, product_id: 2},
  {user_id: 3, product_id: 1}
])
User.create!([
  {email: "duyb0119@gmail.com", encrypted_password: "$2a$10$QqVJSWzapQzgoGdmtByCtuW6qlIChkfCSEyesBfBe15EmxDphBCEa", username: "admin", first_name: "", last_name: "", address: "123 hai ba trung", phone: "0909090909", sex: "Male", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 57, current_sign_in_at: "2017-01-16 10:06:44", last_sign_in_at: "2017-01-16 08:28:26", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", role: "admin", birth_day: "2017-01-16", provider: nil, uid: nil, confirmation_token: "zVBLehrmJNkSzs44wBsp", confirmed_at: "2017-01-04 10:12:59", confirmation_sent_at: "2017-01-04 10:12:44", unconfirmed_email: nil}
])
Cart.create!([
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
])
Comment.create!([
  {user_id: 3, commentable_type: "Product", commentable_id: 3, content: "asdssa", parent_id: nil},
  {user_id: 3, commentable_type: "Product", commentable_id: 1, content: "dsasad", parent_id: nil},
  {user_id: 3, commentable_type: "Product", commentable_id: 4, content: "sdaasasa", parent_id: nil},
  {user_id: 3, commentable_type: "Product", commentable_id: 4, content: "sadsa", parent_id: nil},
  {user_id: 3, commentable_type: "Product", commentable_id: 4, content: "trai nay an do lam\r\n", parent_id: nil}
])
Giftcode.create!([
  {gift_code: "8rmrcZEgGWe4bHPZPzNRHE"},
  {gift_code: "aZHnjQ0KLuXk7qwF82WlrM9"},
  {gift_code: "dQO0MTBVCw9z2G1bmxNR5NCH"},
  {gift_code: "vpHRIy8hR5B14oiDB4Qclh"},
  {gift_code: "sgtgKDaCNbUONWPB7lNyAOZO"},
  {gift_code: "JLsyownrXyEbjErJKrPd3AEab"},
  {gift_code: "Gg7bAmHSICKx1cMtH0Ouh"},
  {gift_code: "BZ6jgoX7OSUy2Fgi0GmRBF"},
  {gift_code: "nwTdcMIrGxmIZ5axSWXysra"},
  {gift_code: "Ws4sKD1AehCYVhXVLTMrnz"},
  {gift_code: "Hzb5QwQqi45QgbI8MEzBNzu"}
])
Newspaper.create!([
  {title: "TÁC DỤNG CỦA MẬT ONG ĐỐI VỚI SỨC KHỎE", content: "<p><strong>TH&Agrave;NH PHẦN DINH DƯỠNG CỦA MẬT ONG</strong></p>\r\n\r\n<p>Quy tr&igrave;nh h&igrave;nh th&agrave;nh của&nbsp;<a href=\"http://greenyhouse.com/tac-dung-cua-mat-ong.html\">mat ong</a>&nbsp;l&agrave; được tạo th&agrave;nh từ chất ngọt trong c&aacute;c b&ocirc;ng hoa do những con ong thu thập được.&nbsp;<a href=\"http://greenyhouse.com/tac-dung-cua-mat-ong.html\">Mật ong</a>&nbsp;l&agrave; hỗn hợp của c&aacute;c loại đường v&agrave; một số th&agrave;nh phần kh&aacute;c. Về th&agrave;nh phần,&nbsp;<a href=\"http://greenyhouse.com/tac-dung-cua-mat-ong.html\">mật ong nguy&ecirc;n chất</a>&nbsp;chủ yếu l&agrave; fructose: chiếm khoảng 38,5% v&agrave; glucose: khoảng 31,0%. C&aacute;c th&agrave;nh phần c&ograve;n lại của mật ong bao gồm maltose, sucrose v&agrave;&nbsp;carbohydrat hỗn hợp&nbsp;kh&aacute;c. Trong mật ong, c&aacute;c&nbsp;vitamin&nbsp;v&agrave; chất kho&aacute;ng chỉ xuất hiện ở dạng vết. Trong th&agrave;nh phần của mật ong cũng chứa một lượng rất nhỏ c&aacute;c hợp chất chức năng như&nbsp;chất chống &ocirc;xy h&oacute;a, bao gồm&nbsp;,&nbsp;vitamin C, chrysin, pinocembrin, pinobanksin,&nbsp;catalase . Th&agrave;nh phần cụ thể của mật phụ thuộc v&agrave;o hoa m&agrave; ong h&uacute;t mật.</p>\r\n\r\n<p>Th&agrave;nh phần th&ocirc;ng dụng của mật ong:</p>\r\n\r\n<p>Fructose: 38,2%</p>\r\n\r\n<p>Glucose: 31,3%</p>\r\n\r\n<p>Sucrose: 1,3%</p>\r\n\r\n<p>Maltose: 7,1%</p>\r\n\r\n<p>Nước: 17,2%</p>\r\n\r\n<p>Khối lượng ph&acirc;n tử của c&aacute;c loại đường cao hơn: 1.5%</p>\r\n\r\n<p>Tro: 0,2%</p>\r\n\r\n<p>C&aacute;c chất kh&aacute;c: 3,2%</p>\r\n\r\n<p>Mật ong c&oacute; Chỉ số glycemic l&agrave; từ 31 đến 78.</p>\r\n\r\n<p>Mật ong c&oacute; khối lượng ri&ecirc;ng&nbsp;l&agrave; 1,36&nbsp;kg/l&iacute;t (nặng hơn nước 36%).</p>\r\n\r\n<p><strong>LỢI &Iacute;CH CỦA MẬT ONG ĐỐI VỚI SỨC KHỎE</strong></p>\r\n\r\n<p><strong>Giảm đau cơ khi vận động:</strong>&nbsp;Mật ong c&oacute; thể tăng cường hiệu suất v&agrave; sức chịu đựng của cơ khi vận động qu&aacute; nhiều, cũng như l&agrave;m giảm đi sự mệt mỏi cơ bắp. Đ&oacute; l&agrave; do sự kết hợp ho&agrave;n hảo của glucose v&agrave; fructose trong mật ong. Glucose được cơ thể hấp thụ dễ d&agrave;ng ngay lập tức v&agrave; nhanh ch&oacute;ng, trong khi đ&oacute;, fructose th&igrave; được hấp thụ dần dần n&oacute; gi&uacute;p duy tr&igrave; năng lượng cho cơ thể.</p>\r\n\r\n<p><img alt=\"\" src=\"/uploads/ckeditor/pictures/2/content_ong-2.jpg\" style=\"width: 648px; height: 495px;\" /></p>\r\n"},
  {title: "MUA CHERRY Ở ĐÂU TẠI TP.HCM?", content: "<p>D&ugrave; gi&aacute; cả&nbsp;<a href=\"http://greenyhouse.com/mua-cherry-o-dau-tai-tp-hcm.html\" target=\"_blank\">Cherry</a>&nbsp;kh&aacute; đắt đỏ nhưng lại được người ti&ecirc;u d&ugrave;ng rất ưa chuộng, được xem như&nbsp;<a href=\"http://greenyhouse.com/\">tr&aacute;i c&acirc;y</a>&nbsp;đặc sản ngoại nhập phải thưởng thức một lần trong đời bởi vị ngon kh&oacute; tả v&agrave; th&agrave;nh phần dinh dưỡng tuyệt vời trong cherry. Tuy nhi&ecirc;n,&nbsp;<a href=\"http://greenyhouse.com/mua-cherry-o-dau-tai-tp-hcm.html\" title=\"MUA CHERRY Ở ĐÂU TẠI TP.HCM?\">mua cherry ở đ&acirc;u</a>&nbsp;để đảm bảo nguồn gốc xuất xứ v&agrave; t&iacute;nh an to&agrave;n trong chất lượng vẫn c&ograve;n l&agrave; c&acirc;u hỏi kh&oacute; khăn của nhiều người.</p>\r\n\r\n<p><img alt=\"\" src=\"/uploads/ckeditor/pictures/3/content_che-2.jpg\" style=\"width: 623px; height: 417px;\" /></p>\r\n\r\n<p><a href=\"http://greenyhouse.com/trai-cherry-uc-nhap-khau-gia-tot-tp-hcm.html\">Cherry &Uacute;c</a>&nbsp;l&agrave; loại tr&aacute;i c&acirc;y c&oacute; nguồn gốc xuất xứ từ v&ugrave;ng kh&iacute; hậu &ocirc;n đới, tại Việt Nam, đ&acirc;y l&agrave; loại cherry được nhập khẩu nhiều do nhu cầu người ti&ecirc;u d&ugrave;ng cao.&nbsp;<a href=\"http://greenyhouse.com/mua-cherry-o-dau-tai-tp-hcm.html\">Cherry</a>&nbsp;thường được b&aacute;n theo m&ugrave;a vụ thu hoạch ở từng v&ugrave;ng, chẳng hạn như cherry Mỹ thường được b&aacute;n nhiều v&agrave;o m&ugrave;a h&egrave;, ở Canada th&igrave; từ th&aacute;ng 5 cho đến th&aacute;ng 9, cherry &Uacute;c thường đạt độ ngon nhất từ cuối th&aacute;ng 11 đến giữa th&aacute;ng 2. Cherry &Uacute;c l&agrave; loại&nbsp;<a href=\"http://greenyhouse.com/\">tr&aacute;i c&acirc;y&nbsp;nhập khẩu</a>&nbsp;được c&aacute;c nh&agrave; khoa học nghi&ecirc;n cứu v&agrave; chứng minh chứa nhiều c&ocirc;ng dụng rất tốt sức khỏe của con người, đặc biệt l&agrave; phụ nữ c&oacute; thai, người bệnh trong giai đoạn cần phục hồi, người lớn tuổi, trẻ nhỏ.</p>\r\n"},
  {title: "CÁCH CHẾ BIẾN HẠT ÓC CHÓ THƠM NGON BỔ DƯỠNG", content: "<p><a href=\"http://greenyhouse.com/qua-oc-cho-mua-o-dau-uy-tin-qua-oc-cho-co-tac-dung-gi.html\" title=\"hat oc cho\">Hạt &oacute;c ch&oacute;</a>&nbsp;l&agrave; loại hạt c&oacute; gi&aacute; trị dinh dưỡng cao, c&oacute; c&ocirc;ng dụng &ldquo;thần kỳ&rdquo; cho sức khỏe. Tuy nhi&ecirc;n, l&agrave; loại hạt nhập khẩu n&ecirc;n c&ograve;n kh&aacute; mới lạ với nhiều người d&ugrave;ng, C&acirc;u hỏi thường đặt ra l&agrave; &ldquo;quả &oacute;c ch&oacute; ăn như thế n&agrave;o&rdquo;,&nbsp;<a href=\"http://greenyhouse.com/cach-che-bien-hat-oc-cho-thom-ngon.html\" title=\"Cach che bien hat oc cho\">c&aacute;ch chế biến quả &oacute;c ch&oacute;</a>, &hellip;. l&agrave; những thắc mắc thường thấy của người d&ugrave;ng đối với loại quả n&agrave;y. &nbsp;H&ocirc;m nay Greeny House xin giới thiệu tới c&aacute;c bạn một số c&aacute;ch chế biến&nbsp;<a href=\"http://greenyhouse.com/qua-oc-cho-mua-o-dau-uy-tin-qua-oc-cho-co-tac-dung-gi.html\" title=\"Hat oc cho\">quả &oacute;c ch&oacute;&nbsp;</a>thơm ngon v&agrave; giữ nguy&ecirc;n dinh dưỡng.</p>\r\n\r\n<p><img alt=\"\" src=\"/uploads/ckeditor/pictures/4/content_cho-2.jpg\" style=\"width: 619px; height: 465px;\" /></p>\r\n\r\n<p>C&aacute;ch chế biến</p>\r\n\r\n<ul>\r\n\t<li>Rửa sạch&nbsp;<a href=\"http://greenyhouse.com/qua-oc-cho-mua-o-dau-uy-tin-qua-oc-cho-co-tac-dung-gi.html\">hạt &oacute;c ch&oacute;</a>&nbsp;đ&atilde; t&aacute;ch vỏ rồi cho v&agrave;o nồi nước đ&atilde; được đun s&ocirc;i luộc ch&iacute;n, vớt ra để nguội, rồi bạn t&aacute;ch phần m&agrave;ng của&nbsp;<a href=\"http://greenyhouse.com/qua-oc-cho-mua-o-dau-uy-tin-qua-oc-cho-co-tac-dung-gi.html\">hạt &oacute;c ch&oacute;</a>&nbsp;cho đỡ ch&aacute;t.</li>\r\n\t<li>Bắc chảo l&ecirc;n bếp đun cho n&oacute;ng chảo, cho vừng v&agrave;o rang khoảng 10-15 ph&uacute;t đến khi ch&iacute;n v&agrave;ng.</li>\r\n\t<li>Cho đường v&agrave; nước d&ugrave;ng v&agrave;o chảo đun s&ocirc;i, cho hạt &oacute;c ch&oacute;, vừng rang v&agrave;o v&agrave; vặn lửa nhỏ.</li>\r\n\t<li>Tiếp tục đảo nhanh tay để m&oacute;n ăn được ch&iacute;n đều. Đun v&agrave;i ph&uacute;t l&agrave; c&oacute; thể bắc ra để nguội thế l&agrave; bạn c&oacute; th&ecirc;m một m&oacute;n ăn ngon từ&nbsp;<a href=\"http://greenyhouse.com/qua-oc-cho-mua-o-dau-uy-tin-qua-oc-cho-co-tac-dung-gi.html\">hạt &oacute;c ch&oacute;</a>&nbsp;rồi nh&eacute;.</li>\r\n</ul>\r\n"}
])
Order.create!([
  {name: "Ron Dam", address: "123 hai ba trung ", phone: "0909090909", email: "abc@gmail.com", pay_type: "Direct", status: "Complete", total_price: 75000, note: "ahahahaha"},
  {name: "d", address: "adsadsa", phone: "0888808089", email: "haha@gmail.com", pay_type: "Direct", status: "Complete", total_price: 90000, note: ""},
  {name: "g", address: "ssss", phone: "1234557891", email: "dsfsdfdsf@gm", pay_type: "Paypal", status: "Uncomplete", total_price: 170000, note: ""}
])
OrderItem.create!([
  {product_id: 4, cart_id: 177, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 9, cart_id: nil, quantity: 1, order_id: nil, order_member_id: 60},
  {product_id: 8, cart_id: 206, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 4, cart_id: nil, quantity: 1, order_id: 2, order_member_id: nil},
  {product_id: 4, cart_id: 183, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 5, cart_id: nil, quantity: 1, order_id: 3, order_member_id: nil},
  {product_id: 8, cart_id: nil, quantity: 19, order_id: nil, order_member_id: 61},
  {product_id: 5, cart_id: nil, quantity: 1, order_id: nil, order_member_id: 55},
  {product_id: 8, cart_id: nil, quantity: 1, order_id: nil, order_member_id: 63},
  {product_id: 9, cart_id: 128, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 2, cart_id: 129, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 9, cart_id: nil, quantity: 1, order_id: nil, order_member_id: 63},
  {product_id: 2, cart_id: 190, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 8, cart_id: 243, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 3, cart_id: nil, quantity: 1, order_id: nil, order_member_id: 56},
  {product_id: 7, cart_id: nil, quantity: 1, order_id: nil, order_member_id: 57},
  {product_id: 1, cart_id: nil, quantity: 1, order_id: 4, order_member_id: nil},
  {product_id: 9, cart_id: nil, quantity: 1, order_id: 4, order_member_id: nil},
  {product_id: 2, cart_id: 139, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 15, cart_id: 276, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 13, cart_id: 276, quantity: 1, order_id: nil, order_member_id: nil},
  {product_id: 8, cart_id: nil, quantity: 20, order_id: nil, order_member_id: 58},
  {product_id: 8, cart_id: nil, quantity: 12, order_id: nil, order_member_id: 59}
])
OrderMember.create!([
  {username: "admin", fullname: " ", address: "", phone: "0909090909", pay_type: "Direct", user_id: 3, status: "Uncomplete", note: "", email: "duyb0119@gmail.com", total_price: 120000, gift_code: ""}
])
Picture.create!([
  {image: "Agar.png", imageable_type: "Product", imageable_id: 1},
  {image: "AttapSeed.png", imageable_type: "Product", imageable_id: 2},
  {image: "Avocado.png", imageable_type: "Product", imageable_id: 3},
  {image: "Banana_Cavendish_.png", imageable_type: "Product", imageable_id: 4},
  {image: "Strawberry.png", imageable_type: "Product", imageable_id: 5},
  {image: "Coconut.png", imageable_type: "Product", imageable_id: 6},
  {image: "chiku.png", imageable_type: "Product", imageable_id: 7},
  {image: "EnvyApple.png", imageable_type: "Product", imageable_id: 8},
  {image: "FragrantPear.png", imageable_type: "Product", imageable_id: 9},
  {image: "GoldKiwi.png", imageable_type: "Product", imageable_id: 10},
  {image: "gia-hat-oc-cho1.jpg", imageable_type: "Category", imageable_id: 2},
  {image: "BrownPear.png", imageable_type: "Category", imageable_id: 3},
  {image: "Strawberry.png", imageable_type: "Category", imageable_id: 1},
  {image: "chiku.png", imageable_type: "Category", imageable_id: 4},
  {image: "honey_dew.jpg", imageable_type: "Product", imageable_id: 12},
  {image: "jambu.jpg", imageable_type: "Product", imageable_id: 13},
  {image: "lychee.jpg", imageable_type: "Product", imageable_id: 14},
  {image: "ong-1.jpg", imageable_type: "Newspaper", imageable_id: 2},
  {image: "che-1.jpg", imageable_type: "Newspaper", imageable_id: 1},
  {image: "cho-1.jpg", imageable_type: "Newspaper", imageable_id: 3},
  {image: "per.jpg", imageable_type: "Product", imageable_id: 15},
  {image: "pome.jpg", imageable_type: "Product", imageable_id: 16},
  {image: "polemo.jpg", imageable_type: "Product", imageable_id: 17}
])
Ckeditor::Picture.create!([
  {data_file_name: "ong-2.jpg", data_content_type: "image/jpeg", data_file_size: 76826, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 648, height: 495},
  {data_file_name: "ong-2.jpg", data_content_type: "image/jpeg", data_file_size: 76826, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 648, height: 495},
  {data_file_name: "che-2.jpg", data_content_type: "image/jpeg", data_file_size: 49217, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 623, height: 417},
  {data_file_name: "cho-2.jpg", data_content_type: "image/jpeg", data_file_size: 84957, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 619, height: 465}
])
